services:
  php:
    image: php:8.3-cli
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test_persistance
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - donnees_mysql:/var/lib/mysql

volumes:
  donnees_mysql:
